<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://maven.apache.org/POM/4.0.0"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cn.poria</groupId>
		<artifactId>poria-platform</artifactId>
		<version>2026-SNAPSHOT</version>
	</parent>

	<version>1.0.0</version>
	<artifactId>poria-upms</artifactId>
	<packaging>pom</packaging>

	<modules>
		<module>poria-upms-api</module>
		<module>poria-upms-biz</module>
	</modules>
</project>
