#!/bin/bash

#打包
mvn clean install
echo "###############Jar打包完成###############"

#Docker镜像打包
docker build -t harbor.shanxi-ncd.cn/ihospital/ih-gateway:1.0.0 .
echo "###############Image打包完成###############"

#Docker镜像推送
docker push harbor.shanxi-ncd.cn/ihospital/ih-gateway:1.0.0
echo "###############Image推送完成###############"

#调用[Rancher API]重新部署
