import { http } from '@/core/http'
export const list = params => http.get('/upms/dict/page', { params })
export const create = data => http.post('/upms/dict', data)
export const update = data => http.put('/upms/dict', data)
export const remove = id => http.delete(`/upms/dict/${id}`)
export const listItems = params => http.get('/upms/dict/item/page', { params })
export const createItem = data => http.post('/upms/dict/item', data)
export const updateItem = data => http.put('/upms/dict/item', data)
export const removeItem = id => http.delete(`/upms/dict/item/${id}`)
export const dictionaryItems = () => http.get('/upms/dict/item/page', { params: { type: 'dict_type', current: 1, size: 1000 }, silent: true }).then(data => data.records || [])
