spring:
  kafka:
    producer:
      acks: 1
      retries: 3
      bootstrap-servers: ${KAFKA_HOST:127.0.0.1:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: "${HOSTNAME}-${CONTEXT_NAME}-KAFKA_SYS_LOG"

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:}
  server:
    port: 7888

sw:
  enabled: ${SW_ENABLED:false}