server:
  port: 4000

spring:
  application:
    name: poria-upms-biz
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:43.136.75.223}
      port: ${REDIS_PORT:26379}
      password: ${REDIS_PASSWORD:zyt20260831aA;}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:zyt20260831aA;}
    url:  jdbc:mysql://${MYSQL_HOST:43.136.75.223}:${MYSQL_PORT:23306}/poria?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 5
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


logging:
  level:
    cn.poria.upms.mapper: debug

auth:
  enable: ${ENCRYPT_ENABLE:true}
  encodeKey: ${ENCODE_KEY:shanxincdJinkang}

write:
  mobiles: ${LOGIN_MOBILES:}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLE:true}
